### ISSUE TITLE
Differet link provided

### ISSUE THREAD

**Issue by akashdsouza** [ember-weekly/newsletter#1]
In issue #156, under the _Reading_ section, the link for **Route Closure Actions in Ember** directs to a different page(https://emberway.io/declarative-templating-in-ember-with-composable-helpers-a70f01d67165#.sqsxzyg11). I believe this is the intended [link](https://emberway.io/route-closure-actions-in-ember-js-d0a7a37a5d1b#.8mcoh9qfi)

**Comment by owain** [comment]
Apologies @akashdsouza, only just saw this. Must have missed the notification. 

Thanks for letting us know, sorry I noticed it so late.
